import js from "@eslint/js";

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                $: "readonly",
                jQuery: "readonly",
                console: "readonly",
                window: "readonly",
                document: "readonly",
                navigator: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                fetch: "readonly",
                FormData: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                setTimeout: "readonly",
                setInterval: "readonly",
                clearTimeout: "readonly",
                clearInterval: "readonly",
                alert: "readonly",
                confirm: "readonly",
                prompt: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                atob: "readonly",
                btoa: "readonly",
                Swal: "readonly",
                global: "readonly",
                MutationObserver: "readonly",
                performance: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                crypto: "readonly",
                XMLHttpRequest: "readonly",
                IntersectionObserver: "readonly",
                requestIdleCallback: "readonly",
                Worker: "readonly",
                CustomEvent: "readonly",
                caches: "readonly",
            },
        },
        rules: {
            "no-console": "warn",
            "no-unused-vars": "warn",
            "prefer-const": "error",
            "no-var": "error",
            "eqeqeq": "error",
            "curly": "error",
            "no-multi-spaces": "error",
            "no-trailing-spaces": "error",
            "quotes": ["error", "double"],
            "semi": ["error", "always"],
        },
    },
    {
        ignores: [
            "node_modules/**",
            "dist/**",
            "build/**",
            "coverage/**",
            "public/**",
            "scripts/**",
            "*.config.js",
        ],
    },
];
